[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true }
server = { workspace = true }
shared = { workspace = true }
platform-dirs = "0.3.0"
tokio = { version = "1.45", features = ["time"] }
