[package]
name = "mobile"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
client = { workspace = true }
server = { workspace = true }
shared = { workspace = true }
chrono = { workspace = true }
tokio = { version = "1.45", features = ["time"] }
<<<<<<< Updated upstream
dioxus-free-icons = { version = "0.10.0-alpha.1", features = ["octicons"] }
postcard = { workspace = true }
=======
dioxus-free-icons = { version = "0.9", features = ["octicons"] }
postcard = { workspace = true }
dioxus-markdown = "0.0"
>>>>>>> Stashed changes

[features]
default = []
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "server/server"]
