CC_x86_64-pc-windows-gnu = "/usr/bin/x86_64-w64-mingw32-gcc"
CXX_x86_64-pc-windows-gnu = "/usr/bin/x86_64-w64-mingw32-g++"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=mold",
    "-Zshare-generics=y",
    "-Zthreads=0",
]

[target.x86_64-pc-windows-gnu]
# linker = "clang"
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
# rustflags = [
#     "-C",
#     "link-args=-target x86_64-pc-windows-gnu -fuse-ld=lld",
# ]
