[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"
rustflags = [
    "-C", "link-arg=-Wl,--eh-frame-hdr",
    "-C", "link-arg=-L${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/21",
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
]
